// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:premises/common/models/common_api_models.dart';
import 'package:premises/common/models/file_object_api_and_request_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CommonFileObjectApiAndRequestModelAdapter());
    registerAdapter(DashboardCarouselPendingCountsApiModelAdapter());
    registerAdapter(PendingCountsApiModelAdapter());
    registerAdapter(PendingTasksApiModelAdapter());
    registerAdapter(PendingTasksDataApiModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CommonFileObjectApiAndRequestModelAdapter());
    registerAdapter(DashboardCarouselPendingCountsApiModelAdapter());
    registerAdapter(PendingCountsApiModelAdapter());
    registerAdapter(PendingTasksApiModelAdapter());
    registerAdapter(PendingTasksDataApiModelAdapter());
  }
}
